[ethereum]
URL = "wss://ropsten.infura.io/ws/v3/$INFURA_ECDSA_ID"
URLRPC = "https://ropsten.infura.io/v3/$INFURA_ECDSA_ID"


[ethereum.account]
Address = "$ETH_ADDRESS"
KeyFile = "/mnt/keystore/keep_wallet.json"

[ethereum.ContractAddresses]
BondedECDSAKeepFactory = "0xb37c8696cD023c11357B37b5b12A9884c9C83784"

[SanctionedApplications]
Addresses = [
    "0x9F3B3bCED0AFfe862D436CB8FF462a454040Af80"
]

[Storage]
DataDir = "/mnt/keep-ecdsa/persistence"
  
[LibP2P]
Peers = ["/dns4/ecdsa-2.test.keep.network/tcp/3919/ipfs/16Uiu2HAmNNuCp45z5bgB8KiTHv1vHTNAVbBgxxtTFGAndageo9Dp",	
"/dns4/ecdsa-3.test.keep.network/tcp/3919/ipfs/16Uiu2HAm8KJX32kr3eYUhDuzwTucSfAfspnjnXNf9veVhB12t6Vf"]
Port = 3919

AnnouncedAddresses = ["/ip4/165.22.74.173/tcp/3920"]

[TSS]
PreParamsGenerationTimeout = "2m30s"